### ISSUE TITLE
Conditional drop on NvList

### ISSUE THREAD

**Issue by jgrund** [jmesmon/rust-libzfs#3]
Consider using `NvList::from_ptr`.

The pointer being passed may be cleaned up elsewhere (out of user's control) and should not be dropped by `NvList` going out of scope.

Should we add a marker that some `NvList` instances should not be dropped?

**Comment by jgrund** [comment]
two things that immediately come to mind are using two implementations of a trait for `NvList`, or having a `should_drop` flag in the struct.

**Comment by jmesmon** [comment]
I think I'd prefer to follow the mechanism used in `std` for `CStr`/`CString` & `str`/`String`.

Unfortunately, I don't think shortening works well here, so maybe `NvList`/`NvListOwned`. 

`NvListOwned` derefs to a `NvList`. `NvList` can abuse transmute a bit to only be formed as a reference from the pointer (rather than having references to a pointer floating around).

Everything non-owned specific would then be impl'd for `NvList` (which can always be gotten from a `NvListOwned`).
